version: '3.8'

services:
  backend:
    image: callicoder/swarm-demo-app:1.0.0
    ports:
      - '8080:8080'
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
